#!/dgr/bin/busybox sh
set -e
. /dgr/bin/functions.sh
isLevelEnabled "debug" && set -x

export ACI_HOME="/dgr/aci-home"

sh

# copy aci dependencies attributes to builder
mkdir -p /dgr/attributes
if [ -d /opt/stage2/${ACI_NAME}/rootfs/dgr/attributes ]; then
  cp -R /opt/stage2/${ACI_NAME}/rootfs/dgr/attributes/* /dgr/attributes
fi

# copy aci attributes to builder
mkdir -p /dgr/attributes/${ACI_NAME}
find ${ACI_HOME}/attributes \( -name "*.yml" -o -name "*.yaml" \) -exec cp {} /dgr/attributes/${ACI_NAME} \;


isLevelEnabled "debug" && echo_purple "Running builder's prestart"
/dgr/bin/prestart

isLevelEnabled "debug" && echo_green "Builder is ready\n"

/dgr/builder/stage2/builder.sh
