#!/dgr/bin/busybox sh
set -e
. /dgr/bin/functions.sh
isLevelEnabled "debug" && set -x

ACI_HOME="/dgr/aci-home"

mkdir -p ${ACI_HOME}/runlevels/prestart-early
mkdir -p ${ACI_HOME}/runlevels/prestart-late
mkdir -p ${ACI_HOME}/runlevels/builder
mkdir -p ${ACI_HOME}/runlevels/build
mkdir -p ${ACI_HOME}/runlevels/build-late
mkdir -p ${ACI_HOME}/runlevels/inherit-build-late
mkdir -p ${ACI_HOME}/runlevels/inherit-build-early
mkdir -p ${ACI_HOME}/attributes
mkdir -p ${ACI_HOME}/files/etc
mkdir -p ${ACI_HOME}/templates/etc
mkdir -p ${ACI_HOME}/tests

cat > ${ACI_HOME}/runlevels/prestart-early/10.prestart-early.sh <<EOF
#!/dgr/bin/busybox sh
. /dgr/bin/functions.sh
isLevelEnabled "debug" && set -x

echo "I'm a prestart early script that is run before templating"
EOF

cat > ${ACI_HOME}/runlevels/prestart-late/10.prestart-late.sh <<EOF
#!/dgr/bin/busybox sh
. /dgr/bin/functions.sh
isLevelEnabled "debug" && set -x

echo "I'm a prestart late script that is run after templating"
EOF

cat > ${ACI_HOME}/runlevels/build/10.install.sh <<EOF
#!/dgr/bin/busybox sh
. /dgr/bin/functions.sh
isLevelEnabled "debug" && set -x

echo "I'm a build script that is run to install applications"
EOF

cat > ${ACI_HOME}/runlevels/builder/10.prepare.sh <<EOF
#!/dgr/bin/busybox sh
.  /dgr/bin/functions.sh
isLevelEnabled "debug" && set -x

echo "I'm builder script file that can use \$ACI_HOME and internet to prepare \$ROOTFS before running build scripts"
EOF

cat > ${ACI_HOME}/runlevels/build-late/10.build-late.sh <<EOF
#!/dgr/bin/busybox sh
. /dgr/bin/functions.sh
isLevelEnabled "debug" && set -x

echo "I'm a build late script that is run to install applications after the copy of files,template,etc..."
EOF

cat > ${ACI_HOME}/runlevels/inherit-build-late/10.inherit-build-late.sh <<EOF
#!/dgr/bin/busybox sh
. /dgr/bin/functions.sh
isLevelEnabled "debug" && set -x

echo "I'm a inherit build late script that is run on this image and all images that have me as dependencies"
EOF

cat > ${ACI_HOME}/runlevels/inherit-build-early/10.inherit-build-early.sh <<EOF
#!/dgr/bin/busybox sh
. /dgr/bin/functions.sh
isLevelEnabled "debug" && set -x

echo "I'm a inherit build early script that is run on this image and all images that have me as dependencies"
EOF

cat > ${ACI_HOME}/files/etc/dummy <<EOF
Dummy file
EOF

cat > ${ACI_HOME}/attributes/attributes.yml <<EOF
default:
  dummy: world
EOF

cat > ${ACI_HOME}/templates/etc/templated.tmpl.cfg <<EOF
---
uid: 0
gid: 0
mode: 0644
checkCmd: true
EOF

cat > ${ACI_HOME}/templates/etc/templated.tmpl <<EOF
Hello {{ .dummy }}
EOF

cat > ${ACI_HOME}/templates/header.partial <<EOF
{{define "header"}}
world
{{end}}
EOF

cat > ${ACI_HOME}/.gitignore <<EOF
target/
EOF

cat > ${ACI_HOME}/tests/dummy.bats <<EOF
#!/dgr/bin/bats

@test "Prestart should template" {
  result="\$(cat /etc/templated)"
  [ "\$result" == "Hello world" ]
}

@test "dgr should copy files" {
  result="\$(cat /etc/dummy)"
  [ "\$result" == "Dummy file" ]
}
EOF

cat > ${ACI_HOME}/tests/wait.sh <<EOF
exit 0
EOF
